### ISSUE TITLE
how to use DI in control?

### ISSUE THREAD

**Issue by adamfoneil** [adamfoneil/MyMusic.Wpf#7]
I tried to add a new `PlayHistory` object to [Player.xaml.cs](https://github.com/adamfoneil/MyMusic.Wpf/blob/master/MyMusic.Wpf/Controls/Player.xaml.cs#L27) but adding to constructor broke the designer, and it said I needed to use ResourceDictionary I think. I didn't understand that.

Please make it so I can use `PlayHistory` within this control

**Comment by sabapathygithub** [comment]
@adamfoneil : Now the `PlayHistory` is injected to the PlayerViewModel constructor.
https://github.com/adamfoneil/MyMusic.Wpf/blob/ec847468cfe71c8aa962fd54b71c33d76c6a1705/MyMusic.Wpf/Controls/PlayerViewModel.cs#L23
